import Head from "next/head";
import Navbar from "./Navbar";

const Layout = ({ children, page }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
          integrity="sha512-Fo3rlrZj/k7ujTnHg4CGR2D7kSs0v4LLanw2qksYuRlEzO+tcaEPQogQ0KaoGN26/zrn20ImR1DfuLWnOo7aBA=="
          crossorigin="anonymous"
          referrerpolicy="no-referrer"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Navbar page={page} />
      </header>
      <main>{children}</main>
    </>
  );
};

export default Layout;
