import Head from "next/head";
import Navbar from "./Navbar";

const Layout = ({ children, page }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Navbar page={page} />
      </header>
      <main>{children}</main>
    </>
  );
};

export default Layout;
